#ifndef __BIGINT_CONSTANTS_H_
#define __BIGINT_CONSTANTS_H_

// Size in bytes of the memory allocated for bigint objects
#ifndef BIGINT_SIZE
    #define BIGINT_SIZE 1024
#endif

// Alignment of bigint buffers in bytes
#define BIGINT_ALIGNMENT 16

// Size of the header informations of a BigInt (one uint64_t field)
#define BIGINT_HEADER_SIZE 8
#define BIGINT_HEADER_PADDING (BIGINT_ALIGNMENT - (BIGINT_HEADER_SIZE % BIGINT_ALIGNMENT))
#define BIGINT_OCTETS_COUNT (BIGINT_SIZE - BIGINT_HEADER_SIZE - BIGINT_HEADER_PADDING)

#if (BIGINT_SIZE / BIGINT_ALIGNMENT) * BIGINT_ALIGNMENT != BIGINT_SIZE
    #error "Please specify BIGINT_SIZE as a multiple of BIGINT_ALIGNMENT"
#endif

// Define bigint tags here:
// ==========================
#define BI_COMMONS_ZERO_TAG 0
#define BI_COMMONS_ONE_TAG 1
#define BI_COMMONS_TWO_TAG 2
#define BI_COMMONS_THREE_TAG 3

#define BI_TESTS_A_TAG 2
#define BI_TESTS_B_TAG 3
#define BI_TESTS_C_TAG 4
#define BI_TESTS_P_TAG 6
#define BI_TESTS_QX_TAG 4
#define BI_TESTS_QY_TAG 4
#define BI_TESTS_X_TAG 7
#define BI_TESTS_X1_TAG 7
#define BI_TESTS_X2_TAG 7
#define BI_TESTS_Y_TAG 8
#define BI_TESTS_Y1_TAG 7
#define BI_TESTS_Y2_TAG 7
#define BI_TESTS_EXPECTED_TAG 9
#define BI_TESTS_PINFX_TAG 2
#define BI_TESTS_PINFY_TAG 3

#define BI_PARAMS_A_TAG 4
#define BI_PARAMS_B_TAG 4
#define BI_PARAMS_GX_TAG 4
#define BI_PARAMS_GY_TAG 4
#define BI_PARAMS_H_TAG 4
#define BI_PARAMS_N_TAG 4
#define BI_PARAMS_P_TAG 4

#define BI_MONTGOMERYMUL_XMONT_TAG 10
#define BI_MONTGOMERYMUL_YMONT_TAG 11
#define BI_DIVIDE_U_TAG 12
#define BI_DIVIDE_V_TAG 13
#define BI_DIVIDE_X1_TAG 14
#define BI_DIVIDE_X2_TAG 15

#define BI_POINTISONCURVE_XSQUARED_TAG 16
#define BI_POINTISONCURVE_XSQUAREDREV_TAG 17
#define BI_POINTISONCURVE_XRESULT_TAG 18
#define BI_POINTISONCURVE_XRESULTREV_TAG 19
#define BI_POINTISONCURVE_YRESULT_TAG 18
#define BI_POINTISONCURVE_YRESULTREV_TAG 19
#define BI_POINTISONCURVE_AX_TAG 20
#define BI_POINTISONCURVE_AXREV_TAG 21

#define BI_POINTADD_NUMERATOR_TAG 0
#define BI_POINTADD_NUMERATORREV_TAG 0
#define BI_POINTADD_DENOMINATOR_TAG 0
#define BI_POINTADD_DENOMINATORREV_TAG 0
#define BI_POINTADD_LAMBDA_TAG 0
#define BI_POINTADD_LAMBDASQUARED_TAG 0
#define BI_POINTADD_LAMBDASQUARED_REV_TAG 0
#define BI_POINTADD_XTWICE_TAG 0
#define BI_POINTADD_XTWICEREV_TAG 0
#define BI_POINTADD_DUMMY_TAG 0
#define BI_POINTADD_X1_TAG 0
#define BI_POINTADD_X1ADDINVERSE_TAG 0
#define BI_POINTADD_Y1_TAG 0
#define BI_POINTADD_Y1ADDINVERSE_TAG 0
#define BI_POINTADD_X2_TAG 0
#define BI_POINTADD_X2ADDINVERSE_TAG 0
#define BI_POINTADD_X3_TAG 0
#define BI_POINTADD_X3ADDINVERSE_TAG 0
#define BI_POINTADD_XADDINVERSE_TAG 0
#define BI_POINTADD_Y3_TAG 0
#define BI_POINTADD_Y3REV_TAG 0
#define BI_POINTADD_X1MINUSX3_TAG 0
#define BI_POINTADD_Y1ADDINVERSE_TAG 0

#define BI_POINTMUL_P1X_TAG 0
#define BI_POINTMUL_P1Y_TAG 0
#define BI_POINTMUL_P2X_TAG 0
#define BI_POINTMUL_P2Y_TAG 0
#define BI_POINTMUL_Q1X_TAG 0
#define BI_POINTMUL_Q1Y_TAG 0
#define BI_POINTMUL_Q2X_TAG 0
#define BI_POINTMUL_Q2Y_TAG 0

// Update the number of tags
// after defining a new one:
#define BI_TAGS_COUNT 16
// ==========================

#endif